kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:13.12.0-alpine
    commands:
    - yarn install
    
  - name: test
    image: node:13.12.0-alpine
    commands:
    - npm test