kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:13.12.0-alpine
    commands:
    - yarn install

  - name: test
    image: node:13.12.0-alpine
    commands:
    - npm run test

  - name: docker-build
    image: plugins/docker
    settings:
      username: ${username}
      password: ${password}
      repo: shannonhung/react-myread
      tags: latest
  

  # - name: notify
  #   image: plugins/slack
  #   settings:
  #     webhook: https://hooks.slack.com/services/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
  #     channel: docker
  #     username: incoming-webhook
  #     template: >
  #       *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)

  #       Commit: {{ repo.name }}/{{ truncate build.commit 8 }}

  #       Branch: {{ build.branch }}

  #       Author: {{ build.author }}

  #       <{{ build.link }}|Visit build page ↗>
  #   when:
  #     branch:
  #       - master
  #     event:
  #       - push
  #     status: [ success, failure ]