pipeline:  
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: docker
    username: incoming-webhook
    when:
      status: [ success, failure ]
