kind: pipeline
type: docker
name: default

steps:
  - name: notify
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: docker
      username: incoming-webhook
      template: >
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)

        Commit: {{ repo.name }}/{{ truncate build.commit 8 }}

        Branch: {{ build.branch }}

        Author: {{ build.author }}

        <{{ build.link }}|Visit build page ↗>
    when:
      branch:
        - master
      event:
        - push
      status: [ success, failure ]
